version: '3'

services:
  siemens_database:
    image: postgres:11
    shm_size: 128M
    container_name: poc_db
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: poc