version: '3'

services:
  siemens_database:
    image: postgres:11
    shm_size: 128M
    container_name: poc_db
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}